### ISSUE TITLE
ValueError: invalid version number '1273'

### ISSUE THREAD

**Issue by skliarie** [RealEnder/dwpa#39]
hashcat 3.60-1 (as shipped by ubuntu 18.04)
Python 2.7.14

```
[~/tmp/hashcat]$ python help_crack.py 
Traceback (most recent call last):
  File "help_crack.py", line 847, in <module>
    hc.run()
  File "help_crack.py", line 738, in run
    self.check_tools()
  File "help_crack.py", line 270, in check_tools
    tools += run_hashcat(['hashcat64.bin', 'hashcat64', 'hashcat'])
  File "help_crack.py", line 224, in run_hashcat
    if t and _run_hashcat(t):
  File "help_crack.py", line 216, in _run_hashcat
    if StrictVersion(output) >= StrictVersion('4.0.1'):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '1273'

```

**Comment by RealEnder** [comment]
Thanks for the report, it will be fixed. Just for reference, we support hashcat 4.0.1+, so packaged 3.60 will not work.
Please use latest binary from here: https://hashcat.net/hashcat/
